### ISSUE TITLE
Number of planes

### ISSUE THREAD

**Issue by kwea123** [czq142857/BSP-NET-original#1]
In figure 5. you mentioned "Note how many planes are unused." So did you take any measures to deal with those redundant planes, as they make the inference slower? Maybe some post-processing step will work?

**Comment by czq142857** [comment]
We did not do anything about the redundant planes. So in the inference time, the redundant planes may make the inference slower (especially when computing the meshes from the BSP-trees). I expect network pruning can be applied here, but I have not implemented it yet.

Please keep in mind that those redundant planes are necessary for training. For example, if the network eventually only needs 100 planes to construct all shapes, you may want to actually use 200-400 planes just to make sure there is enough randomness of the weights after the initialization step.

Best,
Zhiqin
