### ISSUE TITLE
experience result

### ISSUE THREAD

**Issue by flyKite1998** [czq142857/BSP-NET-original#10]
hi，
    Thanks for your great work. I have a question about the experience result. Does table 1 show mean values of five classes? I haven't found corresponding description.

**Comment by czq142857** [comment]
Yes. Table 1 shows the mean values. The per-category results of our method is shown below, in case you need them.

| Ours, no L_overlap | airplane | car     | chair   | lamp    | table   | average (per shape) |
|--------------------|----------|---------|---------|---------|---------|---------------------|
| CD (x1000)         | 0.135    | 0.414   | 0.342   | 1.040   | 0.514   | 0.447               |
| NC                 | 0.876    | 0.870   | 0.852   | 0.823   | 0.862   | 0.858               |
| LFD                | 2573.69  | 1081.58 | 1644.51 | 4300.06 | 1492.62 | 2019.26             |

**Comment by flyKite1998** [comment]
That's what i need .Thanks a lot.
