### ISSUE TITLE
Reproduce Experiment Results

### ISSUE THREAD

**Issue by davina01130117** [czq142857/BSP-NET-original#11]
Thank you for sharing such great work!  I face up some issues in reproducing the experimental results. I have loaded the pretrained weights provided in the repo, but I couldn't obtain the results as good as the values in table1(Table 1: Surface reconstruction quality and comparison for 3D shape autoencoding.)
CD NC LFD
Ours 0.447 0.858 2019.26
Ours + Loverlap 0.448 0.858 2030.3

My results :
no L_overlap | airplane | car | chair | lamp | table | average (per shape)
CD (x1000) | 0.3767 | 0.5829 | 0.8064 | 1.7223 | 0.8743 | 0.8725
NC | 0.8184 | 0.8378 | 0.8027| 0.7081 | 0.8278 |pr 0.7989

Is there any part in this repo I need to change for getting the same results in the paper?
For example, the provided pretrained weight is trained for all category while the results in the paper is trained in individual category?

Thanks for your help!

**Comment by czq142857** [comment]
Yes. The numbers reported in Table 1 are from single-category training on the ShapeNet Part dataset. The provided weights is for Table 3, training on 13 categories from ShapeNet.

If you need to experiment on ShapeNet Part dataset, please download the ready-to-use datasets "in individual hdf5 files" from the readme page, and train the network on them. Datasets "in individual hdf5 files" contain both the 13 categories in ShapeNet and the 5 categories in ShapeNet Part dataset.

Please also see this for detailed numbers on ShapeNet Part dataset.
https://github.com/czq142857/BSP-NET-original/issues/10

**Comment by davina01130117** [comment]
Thank you so much!
