### ISSUE TITLE
Inferring on images of size 128x128 using the 2D BSP-Net

### ISSUE THREAD

**Issue by yeshwanth95** [czq142857/BSP-NET-original#12]
Hi @czq142857,

I have been trying to reproduce the results from your paper on a modified version of the toy dataset which also includes a circle ina addition to the default shapes. When I train 2d BSPnet and infer on the modified toy dataset (images of size 64x64), I am able to obtain results very similar to that in the paper.

However, I also modified the bsp_2d.IMSEG network to accept images of size 128x128. For this, I have simply added another conv+lrelu layer in the encoder so that the outputs of the encoder are shape compatible with the generators.
In this case, the reconstruction quality is significantly poorer. I have used values of 64, 128, 512 for the hyperparameters ef_dim, gf_dim, p_dim respectively, to account for the larger image size and the additional number of convexes and planes required. I have attached the outputs for your reference. It appears that the model particularly fails on the hollow diamond shape, where it is simply predicted as either a solid diamond or as a hollow diamond with a triangular hole. Kindly let me know your thoughts or suggestions on why these kind of artifacts occur when 128x128 patches of the toy dataset are used to train the bspt 2d network.

Looking forward to your reply. Thank you.

**Comment by czq142857** [comment]
Sorry, but I do not have enough information to judge what went wrong. If it works on 64x64, it should work on 128x128, since the shape decoder does not care about the resolution.
