### ISSUE TITLE
Is there anything I missed in this project?

### ISSUE THREAD

**Issue by angelalife** [czq142857/BSP-NET-original#13]
When I tried to train this model, there was a FileNotFoundError.
![bug](https://user-images.githubusercontent.com/39484307/142824367-d7a17f76-3123-42d2-a0f9-f77923ac718e.png)

and this is my context:
![context](https://user-images.githubusercontent.com/39484307/142824065-83145471-e7b5-4f3e-8d2f-68ad66389bd9.png)

Did I miss something important? What should I do to solve this problem?

**Comment by czq142857** [comment]
You were running a testing command. Please check README.md for how to train the model.
