### ISSUE TITLE
how to get mesh output

### ISSUE THREAD

**Issue by hua-wu-que** [czq142857/BSP-NET-original#4]
Hi,

Could you elaborate on how to obtain the water-tight mesh representation from the predictions? Is there any code in this repo regarding this ? Thank you!

**Comment by czq142857** [comment]
Hi,

Please read the readme.md in the Github page for details about watertight. I copied the relevant discussions here:

"The default output mesh is not watertight - adjacent polygons do not share their vertices and edges.
You can enable watertight outputs by replacing function get_mesh with get_mesh_watertight in the testing functions.
Function get_mesh_watertight will merge nearby vertices for each convex to make all convexes watertight."

However, despite the convexes are watertight, the entire shape might not.
Although it could be achieved by CSG operations, we did not implement it as it introduces many unnecessary vertices/faces.

If you could use watertight meshes that are not compact, you can use marching cubes to get them.
There is a function in the code, bsp_ae.test_dae3(FLAGS), that indicates how to use marching cubes on the implicit fields.

Best,
Zhiqin
