### ISSUE TITLE
how to get mesh output with lower number of vertices and faces

### ISSUE THREAD

**Issue by sayands** [czq142857/BSP-NET-original#6]
Hi, 

Could you elaborate on how to generate the meshes with lower number of vertices and faces as shown in Fig 1.(a) of the paper? Is there a piece of code in the current repository to do that?

Thank you!

**Comment by czq142857** [comment]
Please enable watertight outputs as written in the readme file:
"The default output mesh is not watertight - adjacent polygons do not share their vertices and edges. You can enable watertight outputs by replacing function get_mesh with get_mesh_watertight in the testing functions. Function get_mesh_watertight will merge nearby vertices for each convex to make all convexes watertight."

**Comment by sayands** [comment]
Hi, 

Thank you very much for the clarification.
