### ISSUE TITLE
Encoder training for SVR 

### ISSUE THREAD

**Issue by trisct** [czq142857/BSP-NET-original#8]
Thanks for sharing the great work.

I noticed that in your paper you said when training for the SVR problem, you train an autoencoder first and then train another encoder to learn the latent codes. Can you explain the training details of the image encoder training? For example, what loss function do you use in the latent space?

**Comment by czq142857** [comment]
Basically, we used a ResNet encoder with MSE loss on latent codes. If you are interested, please check our code for details.
